#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pypi-fsspec
Version  : 2021.11.1
Release  : 15
URL      : https://files.pythonhosted.org/packages/a5/b1/9c247e65c565e863643763020366b492a6bd4b1fd5854cbc8bdc42bd87ff/fsspec-2021.11.1.tar.gz
Source0  : https://files.pythonhosted.org/packages/a5/b1/9c247e65c565e863643763020366b492a6bd4b1fd5854cbc8bdc42bd87ff/fsspec-2021.11.1.tar.gz
Summary  : File-system specification
Group    : Development/Tools
License  : BSD-3-Clause
Requires: pypi-fsspec-license = %{version}-%{release}
Requires: pypi-fsspec-python = %{version}-%{release}
Requires: pypi-fsspec-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
Provides: fsspec
Provides: fsspec-python
Provides: fsspec-python3
BuildRequires : pypi(pluggy)
BuildRequires : py-python
BuildRequires : pytest
BuildRequires : tox
BuildRequires : pypi(virtualenv)

%description
# filesystem_spec
[![PyPI version](https://badge.fury.io/py/fsspec.svg)](https://pypi.python.org/pypi/fsspec/)
[![Anaconda-Server Badge](https://anaconda.org/conda-forge/fsspec/badges/version.svg)](https://anaconda.org/conda-forge/fsspec)
![Build](https://github.com/fsspec/filesystem_spec/workflows/CI/badge.svg)
[![Docs](https://readthedocs.org/projects/filesystem-spec/badge/?version=latest)](https://filesystem-spec.readthedocs.io/en/latest/?badge=latest)

%package license
Summary: license components for the pypi-fsspec package.
Group: Default

%description license
license components for the pypi-fsspec package.


%package python
Summary: python components for the pypi-fsspec package.
Group: Default
Requires: pypi-fsspec-python3 = %{version}-%{release}

%description python
python components for the pypi-fsspec package.


%package python3
Summary: python3 components for the pypi-fsspec package.
Group: Default
Requires: python3-core
Provides: pypi(fsspec)

%description python3
python3 components for the pypi-fsspec package.


%prep
%setup -q -n fsspec-2021.11.1
cd %{_builddir}/fsspec-2021.11.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1641437130
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
export MAKEFLAGS=%{?_smp_mflags}
python3 -m build --wheel --skip-dependency-check --no-isolation

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pypi-fsspec
cp %{_builddir}/fsspec-2021.11.1/LICENSE %{buildroot}/usr/share/package-licenses/pypi-fsspec/05ee6f4bb52a15a0a29b05ceab4c9648092a8c51
pip install --root=%{buildroot} --no-deps --ignore-installed dist/*.whl
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pypi-fsspec/05ee6f4bb52a15a0a29b05ceab4c9648092a8c51

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
